import type { Metadata } from "next";
import { Geist, Geist_Mono, Tiro_Bangla } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import HomeNavBar from "./_default/HomeNavBar";
import HomeFooter from "./_default/HomeFooter";
import AosWrapper from "./AosWrapper";

// ✅ TiroBangla
const tiroBangla = Tiro_Bangla({
  weight: "400",
  subsets: ["latin", "bengali"], // যদি বাংলা থাকে, তবে এটা ভালো
  variable: "--font-tiro-bangla",
});

// ✅ Geist Sans
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// ✅ Geist Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tiroBangla.variable} antialiased`}
      >
        <AosWrapper>
          <Toaster />
          <HomeNavBar />
          {children}
          <HomeFooter />
        </AosWrapper>
      </body>
    </html>
  );
}
