import type { Metadata } from "next";
import Sidebar from "./components/Sidebar";
import Link from "next/link";
import DashboardHeader from "./components/DashboardHeader";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full h-screen fixed top-0 left-0 z-[100000] bg-white flex flex-col gap-[6px]">
      <Toaster />
      <div className="w-full bg-gray-100 shadow flex justify-center items-center h-[55px]">
        <DashboardHeader />
      </div>
      <div className="w-full flex gap-[6px] relative h-[calc(100vh-59px)]">
        <div className="w-auto">
          <Sidebar />
        </div>
        <div className="w-full h-[calc(100vh-59px)] flex flex-col gap-[6px]">
          <div className="w-full h-[calc(100vh-80px)]  bg-gray-100 shadow rounded overflow-y-auto scrollnone">
            {children}
          </div>
          <div className="w-full h-[40px] bg-gray-200 shadow rounded flex items-center justify-between px-4 text-sm text-gray-600">
            <span>
              © {new Date().getFullYear()} Code-biruni. All rights reserved.
            </span>
            <div className="flex items-center gap-4">
              <Link
                href={"https://code-biruny.vercel.app/pages/company/contact"}
              >
                contact us
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
